#+title: Supernova Explosion Code (SNEC)

[[https://ui.adsabs.harvard.edu/abs/2015ApJ...814...63M/abstract][https://img.shields.io/badge/read-paper-blue.svg?style=flat]] [[https://sntheory.org/SNEC.html][https://img.shields.io/website-up-down-green-red/http/shields.io.svg]]

Copy of the SNEC code for further development. Original distribution
source is at [[https://sntheory.org/SNEC.html]].

* TODO Objectives
- [?] implement inner boundary conditions allowing for infall with no
  back reaction.
- [ ] implement density smoothing self-consistent with boxcar
  composition smoothing

The idea is to track an inner "ghost cell" which always has velocity
and pressure of the cell above (first in the computational domain), so
that no velocity or pressure gradient is created and no back reaction
applies in the domain.


* How to install

First clone this repository, to create the folder =SNEC=. To compile,
you will need =gfortran=, I use the one shipped with the [[http://user.astro.wisc.edu/~townsend/static.php?ref=mesasdk][MESA SDK]], which
can be downloaded from the website, unpacked, and initialized with

#+BEGIN_SRC bash
  export MESASDK_ROOT=/path/to/mesasdk
  source $MESASDK_ROOT/bin/mesasdk_init.sh
#+END_SRC

At the time of writing, this provides

#+BEGIN_SRC bash
  gfortran --version
  GNU Fortran (GCC) 13.3.0
  Copyright (C) 2023 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#+END_SRC

Once =gfortran= is loaded, =cd= into the =SNEC= directory and type:

#+BEGIN_SRC bash
make clean && make
#+END_SRC

You may need to comment/uncomment one line in [[./make.inc][make.inc]] file to point
to the correct location of =Lapack=. The file shipped in this repo is
for installation on linux machines, but there is a commented line for
Mac OS.


* How to run =SNEC=

After editing your =parameters= file according to your needs, and making
sure the output directory exists,

#+BEGIN_SRC bash
 ./snec
#+END_SRC
